<?php
function top_get_categories() {
	$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
	$category = $objectManagerr->create('Magento\Catalog\Model\Category');
    $tree = $category->getTreeModel();
    $tree->load();
    $ids = $tree->getCollection()->addFieldToFilter('is_active', array('eq'=>'1'))->getAllIds();
    $arr = array();
    $arrayCategories = array();
    if ($ids) {
        foreach ($ids as $id) {
            $cat = $objectManagerr->create('Magento\Catalog\Model\Category');
            $cat->load($id);
 
                $arrayCategories[$id] =
                        array("parent_id" => $cat->getParentId(),
                            "name" => $cat->getName(),
                            "cat_id" => $cat->getId(),
                            "cat_level" => $cat->getLevel(),
                            "cat_url" => $cat->getUrl()
                );
        }
        return $arrayCategories;
    }
}
$arrayCategories = top_get_categories();
	
function top_createTree($array, $currentParent, $currLevel = 0, $prevLevel = -1) {
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$catalogSession = $objectManager->create('Magento\Catalog\Model\Session');
    $selected_arr = explode(",", $catalogSession->getTopCatIds());
    $helper = $objectManager->create('CleverSoft\CleverSearchAutocomplete\Helper\Data');
    $searchMultipleCategories = $helper->getSearchMultipleCategories();
    if ($searchMultipleCategories) {
        foreach ($array as $categoryId => $category) {
            if ($currentParent == $category['parent_id']) {
                if ($currLevel > $prevLevel)
                echo '<ul class="top-tree__list">';
                if ($currLevel == $prevLevel)
                    echo " </li> ";
                
                echo '
                    <li class="top-tree__items" id="li_'.$categoryId.'">';
                
                echo '<a href="javascript:;" data-id="'.$categoryId.'">';
                    echo '<span>'.$category['name'].'</span>';
                echo '</a>';
                if ($currLevel > $prevLevel) {
                    $prevLevel = $currLevel;
                }
                $currLevel++;
                top_createTree($array, $categoryId, $currLevel, $prevLevel);
                $currLevel--;
            }
        }
    } else {
        foreach ($array as $categoryId => $category) {
            if ($currentParent == $category['parent_id']) {
                if($currLevel == 0) {
                    if ($currLevel > $prevLevel)
                    echo '<ul class="top-tree__list">';
                    if ($currLevel == $prevLevel)
                        echo " </li> ";
                    
                    echo '
                        <li class="top-tree__items" id="li_'.$categoryId.'">';
                    
                    echo '<a href="javascript:;" data-id="'.$categoryId.'">';
                        echo '<span>'.$category['name'].'</span>';
                    echo '</a>';
                    if ($currLevel > $prevLevel) {
                        $prevLevel = $currLevel;
                    }
                    $currLevel++;
                    top_createTree($array, $categoryId, $currLevel, $prevLevel);
                    $currLevel--;
                }
            }
        }
    }
    
    if ($currLevel == $prevLevel)
        echo " </li></ul> ";
}
?>

<div class="inner">
    <a href="javascript:;" class="current-cat" data-role="trigger">
        <span><?php echo __('All Categories');?></span>
    </a>
    <i class="cs-font clever-icon-down"></i>
</div>
<div id="top_sidetree" style="display: none">
	<div id="top_tree" class="top-tree">
		<ul class="top-tree__parent"><li><a href="javascript:;" data-id=""><?php echo __('All Categories');?></a></li></ul>
		<?php top_createTree($arrayCategories, 2); ?>
	</div>
</div>

<script type="text/javascript">
	require(['jquery'], function($){ 
		$('.current-cat').click(function() {
			$('#top_sidetree').fadeToggle();
		});
        $(document).mouseup(function (e) {
            if (!$('#top_sidetree').is(e.target) && $('#top_sidetree').has(e.target).length === 0)
            {
                $('#top_sidetree').fadeOut();
            }
        });
    	$('#top_tree a').click(function() {
    		var text = $(this).html();
    		var value = $(this).attr('data-id');
		  	$('.current-cat span').html(text);
		  	$('input[name="cat"]').val(value);
            $('#top_sidetree').fadeOut();
		});
		$(document).ready(function(){
			$('.form-group').append('<a href="javascript:;" class="btn-close" style="display: none;"><i class="fa fa-times-circle-o"></i></a>');
		});
		$(document).keypress(function(){
			$('.btn-close').click(function(){
				$('.input-text').val('');
				$('.btn-close').hide();
				if($('.input-text').val('')){
					$('.searchsuite-autocomplete').fadeOut();
				}
			});
 		});
 	});
</script>